# Generated by Django 5.2.15 on 2026-06-06 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='data',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='properties',
            field=models.JSONField(blank=True, default=dict, help_text='Extracted fields'),
        ),
        migrations.AddField(
            model_name='item',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(blank=True, help_text='The crawler config item (type) this matches', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='crawler.item'),
        ),
    ]
