# Generated by Django 5.2.15 on 2026-06-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_remove_item_data_remove_item_name_item_properties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True, help_text='Image URL', max_length=1000),
        ),
    ]
