# Generated by Django 5.2.15 on 2026-06-06 06:01

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('concurrent_requests', models.PositiveIntegerField(default=16, help_text='Max requests processed in parallel.', verbose_name='Concurrency')),
                ('download_delay', models.FloatField(default=0.0, help_text='Seconds to wait between requests to the same site.', verbose_name='Delay')),
                ('cache_enabled', models.BooleanField(default=True, help_text='Cache downloaded responses to disk and reuse them.', verbose_name='Enabled')),
                ('cache_expiration_secs', models.PositiveIntegerField(default=0, help_text='Seconds before a cached response expires (0 = never).', verbose_name='Expiration')),
                ('cache_dir', models.CharField(default='httpcache', help_text='Folder where cached responses are stored.', max_length=255, verbose_name='Directory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Item title/label', max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('is_template', models.BooleanField(default=False, help_text='An extraction template (its Props drive parsing)')),
                ('rank', models.FloatField(db_index=True, default=0.0, help_text='Importance score')),
                ('css', models.CharField(blank=True, help_text='Root CSS selector', max_length=500)),
                ('xpath', models.CharField(blank=True, help_text='Root XPath expression', max_length=500)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('crawlers', models.ManyToManyField(blank=True, help_text='The crawlers this item belongs to', related_name='items', to='crawler.crawler')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Broader item this one is nested under', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='crawler.item')),
            ],
        ),
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('url', 'URL'), ('datetime', 'DateTime'), ('json', 'JSON')], default='string', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('many', models.BooleanField(default=False, help_text='Holds a list of values')),
                ('description', models.TextField(blank=True)),
                ('css', models.CharField(blank=True, help_text='CSS selector', max_length=500)),
                ('xpath', models.CharField(blank=True, help_text='XPath expression', max_length=500)),
                ('regex', models.CharField(blank=True, help_text='Regex pattern', max_length=500)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='props', to='crawler.item')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('allow', models.CharField(blank=True, help_text='Regex links must match', max_length=500)),
                ('deny', models.CharField(blank=True, help_text='Regex links must NOT match', max_length=500)),
                ('allow_domains', models.CharField(blank=True, max_length=500)),
                ('deny_domains', models.CharField(blank=True, max_length=500)),
                ('restrict_css', models.CharField(blank=True, max_length=500)),
                ('restrict_xpaths', models.CharField(blank=True, max_length=500)),
                ('callback', models.CharField(blank=True, help_text='Spider method to parse matched pages', max_length=120)),
                ('follow', models.BooleanField(default=True)),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='crawler.crawler')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='e.g. example.com', max_length=255)),
                ('start_url', models.URLField(blank=True, help_text='Optional seed URL to begin crawling from')),
                ('enabled', models.BooleanField(default=True)),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='crawler.crawler')),
            ],
            options={
                'ordering': ['host'],
                'unique_together': {('crawler', 'host')},
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='crawler_ite_name_b62226_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tree_id', 'lft'], name='crawler_item_tree_id_lft_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prop',
            unique_together={('item', 'name')},
        ),
    ]
