# Generated by Django 5.2.15 on 2026-06-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawler',
            name='ollama_model',
            field=models.CharField(blank=True, default='llama3.2', help_text='Offline Ollama model used to parse pages into items.', max_length=120),
        ),
    ]
